version: 2.1

commands:
  destroy_environment:
    steps:
      - run: chmod u+x destroy.yml
      - run: 
          name: Destroy environment
          command: ./destroy.yml

jobs:
  create_infrastructure:
    working_directory: ~/infrastructure
    docker: 
      - image: amazon/aws-cli:latest
    steps:
        - checkout
        - run: ls -a 
        - run: mkdir ~/.aws     
        - run: echo "[default]" >> ~/.aws/credentials
        - run: echo "aws_access_key_id=$aws_access_key_id" >> ~/.aws/credentials
        - run: echo "aws_secret_access_key=$aws_secret_access_key" >> ~/.aws/credentials
        - run: chmod u+x setup.sh
        - persist_to_workspace:
            root: ~/infrastructure
            paths:
              - '*'
        - run: ./setup.sh      
      
              
  configure_infrastructure:
    working_directory: ~/infrastructure
    docker: 
      - image: python:3.7-alpine3.11
    steps:  
      - add_ssh_keys:
          fingerprints: ["1c:85:2e:39:d5:fb:01:5e:84:25:a8:b8:ad:86:cc:14"]
      - run:
          name: install dependencies
          command: |
            apk add --update ansible
      - run: 
          name: configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
              
  smoke_test:
    working_directory: ~/infrastructure
    docker:
      - image: python:3.7-alpine3.11         
    steps:
        - attach_workspace:
            at: ~/infrastructure
        - run: ls -a
        - run:
            name: install curl
            command: |
              apk --no-cache add curl
        - run: chmod u+x smoke.sh
        - run: return 1 #simulate error
        - run:
            name: Destroy environment
            command: destroy_environment
            when: on_fail

        

workflows:
  pipeline:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires: 
            - create_infrastructure
      - smoke_test:
          requires: 
            - configure_infrastructure
